// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: exchange.proto

package radwallet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExchangeClient is the client API for Exchange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeClient interface {
	ListExchanges(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ExchangeList, error)
	GetUserPatrimony(ctx context.Context, in *ExchangeId, opts ...grpc.CallOption) (*UserPatrimony, error)
	GetUserInvested(ctx context.Context, in *ExchangeId, opts ...grpc.CallOption) (*UserInvested, error)
	GetCoinDetail(ctx context.Context, in *CoinDetail, opts ...grpc.CallOption) (*CoinDetailResponse, error)
}

type exchangeClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeClient(cc grpc.ClientConnInterface) ExchangeClient {
	return &exchangeClient{cc}
}

func (c *exchangeClient) ListExchanges(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ExchangeList, error) {
	out := new(ExchangeList)
	err := c.cc.Invoke(ctx, "/radhark.radwallet.Exchange/ListExchanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeClient) GetUserPatrimony(ctx context.Context, in *ExchangeId, opts ...grpc.CallOption) (*UserPatrimony, error) {
	out := new(UserPatrimony)
	err := c.cc.Invoke(ctx, "/radhark.radwallet.Exchange/GetUserPatrimony", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeClient) GetUserInvested(ctx context.Context, in *ExchangeId, opts ...grpc.CallOption) (*UserInvested, error) {
	out := new(UserInvested)
	err := c.cc.Invoke(ctx, "/radhark.radwallet.Exchange/GetUserInvested", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeClient) GetCoinDetail(ctx context.Context, in *CoinDetail, opts ...grpc.CallOption) (*CoinDetailResponse, error) {
	out := new(CoinDetailResponse)
	err := c.cc.Invoke(ctx, "/radhark.radwallet.Exchange/GetCoinDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeServer is the server API for Exchange service.
// All implementations must embed UnimplementedExchangeServer
// for forward compatibility
type ExchangeServer interface {
	ListExchanges(context.Context, *emptypb.Empty) (*ExchangeList, error)
	GetUserPatrimony(context.Context, *ExchangeId) (*UserPatrimony, error)
	GetUserInvested(context.Context, *ExchangeId) (*UserInvested, error)
	GetCoinDetail(context.Context, *CoinDetail) (*CoinDetailResponse, error)
	mustEmbedUnimplementedExchangeServer()
}

// UnimplementedExchangeServer must be embedded to have forward compatible implementations.
type UnimplementedExchangeServer struct {
}

func (UnimplementedExchangeServer) ListExchanges(context.Context, *emptypb.Empty) (*ExchangeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExchanges not implemented")
}
func (UnimplementedExchangeServer) GetUserPatrimony(context.Context, *ExchangeId) (*UserPatrimony, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPatrimony not implemented")
}
func (UnimplementedExchangeServer) GetUserInvested(context.Context, *ExchangeId) (*UserInvested, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInvested not implemented")
}
func (UnimplementedExchangeServer) GetCoinDetail(context.Context, *CoinDetail) (*CoinDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoinDetail not implemented")
}
func (UnimplementedExchangeServer) mustEmbedUnimplementedExchangeServer() {}

// UnsafeExchangeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeServer will
// result in compilation errors.
type UnsafeExchangeServer interface {
	mustEmbedUnimplementedExchangeServer()
}

func RegisterExchangeServer(s grpc.ServiceRegistrar, srv ExchangeServer) {
	s.RegisterService(&Exchange_ServiceDesc, srv)
}

func _Exchange_ListExchanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServer).ListExchanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radhark.radwallet.Exchange/ListExchanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServer).ListExchanges(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exchange_GetUserPatrimony_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServer).GetUserPatrimony(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radhark.radwallet.Exchange/GetUserPatrimony",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServer).GetUserPatrimony(ctx, req.(*ExchangeId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exchange_GetUserInvested_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServer).GetUserInvested(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radhark.radwallet.Exchange/GetUserInvested",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServer).GetUserInvested(ctx, req.(*ExchangeId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exchange_GetCoinDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoinDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServer).GetCoinDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/radhark.radwallet.Exchange/GetCoinDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServer).GetCoinDetail(ctx, req.(*CoinDetail))
	}
	return interceptor(ctx, in, info, handler)
}

// Exchange_ServiceDesc is the grpc.ServiceDesc for Exchange service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exchange_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "radhark.radwallet.Exchange",
	HandlerType: (*ExchangeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListExchanges",
			Handler:    _Exchange_ListExchanges_Handler,
		},
		{
			MethodName: "GetUserPatrimony",
			Handler:    _Exchange_GetUserPatrimony_Handler,
		},
		{
			MethodName: "GetUserInvested",
			Handler:    _Exchange_GetUserInvested_Handler,
		},
		{
			MethodName: "GetCoinDetail",
			Handler:    _Exchange_GetCoinDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exchange.proto",
}
